---
date: '`r format(Sys.Date(), "%d\\. %m\\. %Y")`'  # today
#logo: /Users/sebastiansaueruser/Pictures/Logos/logo.jpg


#bibliography: 
#  - /Users/sebastiansaueruser/Literatur/refmgt/library-zotero.bib
#biblio-style: "apa"
# csl: "/Users/sebastiansaueruser/Literatur/refmgt/apa.csl"




# fontfamily: lmodern
fontsize: 11pt
# geometry: margin=1.3in

classoption:
  - a4paper
  - oneside
  #- more options here, see rmarkdown documentation 
lang: de-De
numbersections: yes
csquotes: TRUE

#toc_depth: 2

title: "Vignette for package yart"
subtitle: "NOT via an r package, but as a pandoc-template"
author: "Sebastian Sauer"
course: 'Seminar: Solutions to All and Nothing'
address: My Road 1, 12345 Somesmalltown
field: Sophism
#logo: examples/logo.png  # insert path to your logo
referee: 'Referee: Prof. Dr. I. Weiss-Ois'
ID: 'My Immatriculation ID: 12345679'


abstract: |
  Yart provides an RMarkdown template for rendering TeX based PDFs. It provides a format suitable for academic settings. The typical RMarkdown variables may be used. In additiion, some variabels useful for academic reports have been added such as name of referee, due date, course title, field of study, addres of author, and logo, and a few more maybe. In addition, paper format (eg., paper size, margins) may be adjusted; the babel language set of Latex is supported. Those variables are defined in the yaml header of the yart document. Adjust those variables to your need. Note that citations, figure/ table referencing is possible due to the underlying pandoc magic. This template is not much more than setting some of the variables provided by rmarkdown (pandoc, knitr, latex, and more), credit is due to the original authors. Please reade the rmarkdown documentation for detailled information on how to use rmarkdown and how to change settings.
output: 
  pdf_document:
    latex_engine: xelatex
    toc: no
    toc_depth: 2
    citation_package: biblatex
#    pandoc_args:
#    - --filter
#    - /Users/sebastiansaueruser/exec/typography.py/typography.py
     
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# My Section Header 1


Please see the documentation of [RMarkdown](http://rmarkdown.rstudio.com/) for more details on how to write RMarkdown documents.

Download a testlogo from here: <https://raw.githubusercontent.com/sebastiansauer/yart/master/docs/logo.png> and uncomment the respective line in the header.

For finetuning of design options, please check the tex template. There you will find some variables such as `$classoption$`. Those variables may be addressed in the yaml header of the yart file.



## My Section Header 2


"Lorem ipsum" dolor sit amet, consectetur adipiscing elit. Proin mollis
dolor vitae tristique eleifend. Quisque non ipsum sit amet velit
malesuada consectetur. Praesent vel facilisis leo. Sed facilisis
varius orci, ut aliquam lorem malesuada in. Morbi nec purus at nisi
fringilla varius non ut dui. Pellentesque bibendum sapien velit. Nulla
purus justo, congue eget enim a, elementum sollicitudin eros. Cras
porta augue ligula, vel adipiscing odio ullamcorper eu. In tincidunt
nisi sit amet tincidunt tincidunt. Maecenas elementum neque eget dolor
[egestas fringilla](http://example.com):

